gpio_radio_pin_bcm = 17

bit1_length_micros = 3900
bit0_length_micros = 1800
first_sync_length_micros = 7900
last_sync_length_micros = 15900
signal_variance_micros = 500

influx_host = "localhost"
influx_port = 8086
influx_database = "rs_weather_sensors"